[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "interp"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[workspace]
members = ["interp-macros"]

[dependencies]
take = "0.1.0"
interp-macros = { path = "interp-macros" }
proc-macro-hack = "0.5"
